create table
  public.templates (
    id bigint generated by default as identity,
    name text not null,
    family text not null,
    config_json jsonb null,
    created_at timestamp with time zone not null default now(),
    constraint templates_pkey primary key (id)
  ) tablespace pg_default;