create table
  public.optimizations (
    id bigint generated by default as identity,
    user_id uuid not null,
    resume_id bigint not null,
    jd_id bigint not null,
    match_score real null,
    gaps_json jsonb null,
    rewrite_json jsonb null,
    template_key text null,
    output_paths jsonb null,
    status text null,
    created_at timestamp with time zone not null default now(),
    constraint optimizations_pkey primary key (id),
    constraint optimizations_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade,
    constraint optimizations_resume_id_fkey foreign key (resume_id) references resumes (id) on delete cascade,
    constraint optimizations_jd_id_fkey foreign key (jd_id) references job_descriptions (id) on delete cascade
  ) tablespace pg_default;