-- Enable Row Level Security on all core tables
-- This is a critical security fix

ALTER TABLE IF EXISTS profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resumes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_descriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS optimizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS design_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS design_customizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resume_design_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS chat_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS resume_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS amendment_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS applications ENABLE ROW LEVEL SECURITY;
