create table
  public.job_descriptions (
    id bigint generated by default as identity,
    user_id uuid not null,
    source_url text null,
    title text null,
    company text null,
    raw_text text null,
    clean_text text null,
    extracted_json jsonb null,
    embeddings vector null,
    created_at timestamp with time zone not null default now(),
    constraint job_descriptions_pkey primary key (id),
    constraint job_descriptions_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;