#!/bin/bash
# PostHog Dashboard Setup Script
# This script provides step-by-step instructions for setting up the Week 1 Launch dashboard

echo "═══════════════════════════════════════════════"
echo "  PostHog Dashboard Setup - Week 1 Launch"
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 MANUAL SETUP REQUIRED"
echo ""
echo "PostHog doesn't support CLI dashboard creation yet."
echo "Follow these steps to create your dashboard:"
echo ""
echo "1. Go to: https://app.posthog.com"
echo "2. Click 'Dashboards' in the left sidebar"
echo "3. Click 'New Dashboard'"
echo "4. Name it: 'Week 1 Launch Metrics'"
echo "5. Description: 'Critical metrics for launch week'"
echo ""
echo "Then add these 7 insights (click '+ Add insight' for each):"
echo ""
echo "═══════════════════════════════════════════════"
echo "  INSIGHT 1: Anonymous ATS Checks"
echo "═══════════════════════════════════════════════"
echo "Type: Trends"
echo "Event: ats_check_anonymous (or \$pageview with filter: path contains '/api/public/ats-check')"
echo "Date range: Last 7 days"
echo "Interval: Daily"
echo "Display: Line chart"
echo "Goal: 200+ by end of Week 1"
echo ""
read -p "Press Enter when Insight 1 is added..."
echo ""
echo "═══════════════════════════════════════════════"
echo "  INSIGHT 2: Signup Funnel"
echo "═══════════════════════════════════════════════"
echo "Type: Funnel"
echo "Step 1: ats_check_anonymous"
echo "Step 2: \$pageview (filter: path = '/auth/signup')"
echo "Step 3: user_signed_up"
echo "Conversion window: 1 day"
echo "Breakdown: utm_source"
echo "Goal: 20%+ conversion rate"
echo ""
read -p "Press Enter when Insight 2 is added..."
echo ""
echo "═══════════════════════════════════════════════"
echo "  INSIGHT 3: Traffic Sources"
echo "═══════════════════════════════════════════════"
echo "Type: Trends"
echo "Event: \$pageview"
echo "Breakdown: utm_source"
echo "Date range: Last 7 days"
echo "Display: Stacked area chart"
echo ""
read -p "Press Enter when Insight 3 is added..."
echo ""
echo "═══════════════════════════════════════════════"
echo "  INSIGHT 4: Social Shares"
echo "═══════════════════════════════════════════════"
echo "Type: Trends"
echo "Event: social_share_clicked"
echo "Breakdown: platform"
echo "Date range: Last 7 days"
echo "Display: Bar chart"
echo "Goal: 10+ shares"
echo ""
read -p "Press Enter when Insight 4 is added..."
echo ""
echo "═══════════════════════════════════════════════"
echo "  INSIGHT 5: Newsletter Signups"
echo "═══════════════════════════════════════════════"
echo "Type: Trends"
echo "Event: newsletter_subscribed"
echo "Date range: Last 7 days"
echo "Display: Big number with comparison"
echo "Goal: 20+"
echo ""
read -p "Press Enter when Insight 5 is added..."
echo ""
echo "═══════════════════════════════════════════════"
echo "  INSIGHT 6: Top Pages"
echo "═══════════════════════════════════════════════"
echo "Type: Trends"
echo "Event: \$pageview"
echo "Breakdown: \$current_url"
echo "Filter: Exclude paths containing '/api/' and '/assets/'"
echo "Display: Table"
echo ""
read -p "Press Enter when Insight 6 is added..."
echo ""
echo "═══════════════════════════════════════════════"
echo "  INSIGHT 7: Avg Session Duration"
echo "═══════════════════════════════════════════════"
echo "Type: Trends"
echo "Event: \$pageview"
echo "Math: Average of \$session_duration"
echo "Date range: Last 7 days"
echo "Display: Line chart"
echo "Target: >120 seconds (2 minutes)"
echo ""
read -p "Press Enter when Insight 7 is added..."
echo ""
echo "✅ Dashboard setup complete!"
echo ""
echo "💡 PRO TIP: Pin this dashboard to your favorites"
echo "    Click the star icon in the top right"
echo ""
echo "📊 NEXT STEPS:"
echo "   1. Set dashboard to auto-refresh every 5 minutes"
echo "   2. Share dashboard URL with your team (if applicable)"
echo "   3. Check it daily at 9am during launch week"
echo ""
echo "Dashboard config also available at:"
echo "   scripts/posthog-dashboard-config.json"
echo ""
