create table if not exists
  public.resumes (
    id bigint generated by default as identity,
    user_id uuid not null,
    filename text null,
    storage_path text null,
    raw_text text null,
    canonical_data jsonb null,
    embeddings vector null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone null,
    constraint resumes_pkey primary key (id),
    constraint resumes_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
  ) tablespace pg_default;
